### ISSUE TITLE
xacro:dhand_adapter_gazebo_v0 issue

### ISSUE THREAD

**Issue by MuratCA77** [Nishida-Lab/dhand_ros_pkg#7]
It is giving the following issue when I run roslaunch sia5_with_dhand.launch file:

unknown macro name: xacro:dhand_adapter_gazebo_v0

**Comment by RyodoTanaka** [comment]
@MuratCA77 
I'm sorry for so late reply....
I confirmed the same error.
That was occurred by missing the file include.
But now, I fixed that in the latest commit.
So, if you still have this error, please update to the latest version on master branch and try it please.
Best.

**Comment by MoriKen254** [comment]
sounds perfect according to  https://travis-ci.org/Nishida-Lab/dhand_ros_pkg

Close!
